

strategy_json = [{"MAIN": "AltcoinTrader15"},
                 {"HIGH": "BuyerDevHigh"},
                 {"MID": "BuyerDevMid"},
                 {"LOW": "BuyerDevLow"},
                 {"LONG UPTREND": "BuyerDevLongUptrend"},
                 {"SLOW DOWNTREND": "BuyerDevSlowDowntrend"},
                 {"LONG DOWNTREND": "BuyerDevLongDowntrend"},
                 {"DOWNTREND UPSWING": "BuyerDevDowntrendUpswing"},
                 {"DANGER ZONE": "BuyerDevBottomDanger"},
                 {"UPPER DANGER ZONE": "BuyerDevUpperDanger"},
                 {"ANY": "BuyerDevAny"},
                 {"NOTREND": "BuyerDevNotrend"},
                 {"HIGH SELL": "SellerDevHigh"},
                 {"MID SELL": "SellerDevMid"},
                 {"LOW SELL": "SellerDevLow"},
                 {"LONG UPTREND SELL": "SellerDevLongUptrend"},
                 {"SLOW DOWNTREND SELL": "SellerDevSlowDowntrend"},
                 {"LONG DOWNTREND SELL": "SellerDevLongDowntrend"},
                 {"DANGER ZONE SELL": "SellerDevBottomDanger"},
                 {"UPPER DANGER ZONE SELL": "SellerDevUpperDanger"},
                 {"ANY SELL": "SellerDevAny"},
                 {"NOTREND SELL": "SellerDevNotrend"},

                 # #DRAFT RULES
                 # {"BUY 1": "x_Buy1"},
                 # {"BUY 2": "x_Buy2"},
                 # {"BUY 3": "x_Buy3"},
                 # {"BUY 4": "x_Buy4"},
                 # {"BUY 5": "x_Buy5"},



                 #DRAFT RULES
                 {"Template Buy": "TemplateBuy"},
                 {"Template Buy NFI": "TemplateBuyNfi"},
                 {"Template Sell": "TemplateSellNfi"},
                 {"Template Sell NFI": "TemplateSellNfi"},



                 #LOW RULES
                 {"LOW BUY 1": "x_BUY_LOW1"},
                 {"LOW BUY 2": "x_BUY_LOW2"},
                 {"LOW BUY 3": "x_BUY_LOW3"},
                 {"LOW BUY 4": "x_BUY_LOW4"},
                 {"LOW BUY 5": "x_BUY_LOW5"},
                 {"LOW BUY 6": "x_BUY_LOW6"},
                 {"LOW BUY 7": "x_BUY_LOW7"},
                 {"LOW BUY 8": "x_BUY_LOW8"},
                 {"LOW BUY 9": "x_BUY_LOW9"},
                 {"LOW BUY 10": "x_BUY_LOW10"},
                 {"LOW BUY 11": "x_BUY_LOW11"},
                 {"LOW BUY 12": "x_BUY_LOW12"},
                 {"LOW BUY 13": "x_BUY_LOW13"},
                 {"LOW BUY 14": "x_BUY_LOW14"},
                 {"LOW BUY 15": "x_BUY_LOW15"},
                 {"LOW BUY 16": "x_BUY_LOW16"},
                 {"LOW BUY 17": "x_BUY_LOW17"},

                 #MID RULES
                 {"MID BUY 1": "x_BUY_MID1"},
                 {"MID BUY 2": "x_BUY_MID2"},
                 {"MID BUY 3": "x_BUY_MID3"},
                 {"MID BUY 4": "x_BUY_MID4"},
                 {"MID BUY 5": "x_BUY_MID5"},
                 {"MID BUY 6": "x_BUY_MID6"},
                 {"MID BUY 7": "x_BUY_MID7"},
                 {"MID BUY 8": "x_BUY_MID8"},
                 {"MID BUY 9": "x_BUY_MID9"},
                 {"MID BUY 10": "x_BUY_MID10"},
                 {"MID BUY 11": "x_BUY_MID11"},
                 {"MID BUY 12": "x_BUY_MID12"},
                 {"MID BUY 13": "x_BUY_MID13"},
                 {"MID BUY 14": "x_BUY_MID14"},
                 {"MID BUY 15": "x_BUY_MID15"},
                 {"MID BUY 16": "x_BUY_MID16"},
                 {"MID BUY 17": "x_BUY_MID17"},

                 #HIGH RULES
                 {"HIGH BUY 1": "x_BUY_HIGH1"},
                 {"HIGH BUY 2": "x_BUY_HIGH2"},
                 {"HIGH BUY 3": "x_BUY_HIGH3"},
                 {"HIGH BUY 4": "x_BUY_HIGH4"},
                 {"HIGH BUY 5": "x_BUY_HIGH5"},
                 {"HIGH BUY 6": "x_BUY_HIGH6"},
                 {"HIGH BUY 7": "x_BUY_HIGH7"},
                 {"HIGH BUY 8": "x_BUY_HIGH8"},
                 {"HIGH BUY 9": "x_BUY_HIGH9"},
                 {"HIGH BUY 10": "x_BUY_HIGH10"},
                 {"HIGH BUY 11": "x_BUY_HIGH11"},
                 {"HIGH BUY 12": "x_BUY_HIGH12"},
                 {"HIGH BUY 13": "x_BUY_HIGH13"},
                 {"HIGH BUY 14": "x_BUY_HIGH14"},
                 {"HIGH BUY 15": "x_BUY_HIGH15"},
                 {"HIGH BUY 16": "x_BUY_HIGH16"},
                 {"HIGH BUY 17": "x_BUY_HIGH17"},
                 {"HIGH BUY 18": "x_BUY_HIGH18"},
                 {"HIGH BUY 19": "x_BUY_HIGH19"},
                 {"HIGH BUY 20": "x_BUY_HIGH20"},

                 #LONG UPTREND RULES
                 {"LONG UPTREND BUY 1": "x_BUY_LONG_UPTREND1"},
                 {"LONG UPTREND BUY 2": "x_BUY_LONG_UPTREND2"},
                 {"LONG UPTREND BUY 3": "x_BUY_LONG_UPTREND3"},
                 {"LONG UPTREND BUY 4": "x_BUY_LONG_UPTREND4"},
                 {"LONG UPTREND BUY 5": "x_BUY_LONG_UPTREND5"},
                 {"LONG UPTREND BUY 6": "x_BUY_LONG_UPTREND6"},
                 {"LONG UPTREND BUY 7": "x_BUY_LONG_UPTREND7"},
                 {"LONG UPTREND BUY 8": "x_BUY_LONG_UPTREND8"},
                 {"LONG UPTREND BUY 9": "x_BUY_LONG_UPTREND9"},
                 {"LONG UPTREND BUY 10": "x_BUY_LONG_UPTREND10"},
                 {"LONG UPTREND BUY 11": "x_BUY_LONG_UPTREND11"},
                 {"LONG UPTREND BUY 12": "x_BUY_LONG_UPTREND12"},
                 {"LONG UPTREND BUY 13": "x_BUY_LONG_UPTREND13"},
                 {"LONG UPTREND BUY 14": "x_BUY_LONG_UPTREND14"},
                 {"LONG UPTREND BUY 15": "x_BUY_LONG_UPTREND15"},
                 {"LONG UPTREND BUY 16": "x_BUY_LONG_UPTREND16"},
                 {"LONG UPTREND BUY 17": "x_BUY_LONG_UPTREND17"},
                 {"LONG UPTREND BUY 18": "x_BUY_LONG_UPTREND18"},
                 {"LONG UPTREND BUY 19": "x_BUY_LONG_UPTREND19"},
                 {"LONG UPTREND BUY 20": "x_BUY_LONG_UPTREND20"},


                 #LONG DOWNTREND RULES
                 {"LONG DOWNTREND BUY 1, test DZ": "x_BUY_LONG_DOWNTREND1"},
                 {"LONG DOWNTREND BUY 2, test DZ": "x_BUY_LONG_DOWNTREND2"},
                 {"LONG DOWNTREND BUY 3, test DZ": "x_BUY_LONG_DOWNTREND3"},
                 {"LONG DOWNTREND BUY 4, test DZ": "x_BUY_LONG_DOWNTREND4"},
                 {"LONG DOWNTREND BUY 5, test DZ": "x_BUY_LONG_DOWNTREND5"},
                 {"LONG DOWNTREND BUY 6, test DZ": "x_BUY_LONG_DOWNTREND6"},
                 {"LONG DOWNTREND BUY 7, test DZ": "x_BUY_LONG_DOWNTREND7"},
                 {"LONG DOWNTREND BUY 8, test DZ": "x_BUY_LONG_DOWNTREND8"},
                 {"LONG DOWNTREND BUY 9, test DZ": "x_BUY_LONG_DOWNTREND9"},
                 {"LONG DOWNTREND BUY 10 ,test DZ": "x_BUY_LONG_DOWNTREND10"},
                 {"LONG DOWNTREND BUY 11 ,test DZ": "x_BUY_LONG_DOWNTREND11"},
                 {"LONG DOWNTREND BUY 12 ,test DZ": "x_BUY_LONG_DOWNTREND12"},
                 {"LONG DOWNTREND BUY 13 ,test DZ": "x_BUY_LONG_DOWNTREND13"},
                 {"LONG DOWNTREND BUY 14 ,test DZ": "x_BUY_LONG_DOWNTREND14"},
                 {"LONG DOWNTREND BUY 15 ,test DZ": "x_BUY_LONG_DOWNTREND15"},
                 {"LONG DOWNTREND BUY 16 ,test DZ": "x_BUY_LONG_DOWNTREND16"},
                 {"LONG DOWNTREND BUY 17 ,test DZ": "x_BUY_LONG_DOWNTREND17"},
                 {"LONG DOWNTREND BUY 18 ,test DZ": "x_BUY_LONG_DOWNTREND18"},
                 {"LONG DOWNTREND BUY 19 ,test DZ": "x_BUY_LONG_DOWNTREND19"},
                 {"LONG DOWNTREND BUY 20 ,test DZ": "x_BUY_LONG_DOWNTREND20"},


                 # DANGER ZONE RULES
                 {"DANGER ZONE BUY 1 ,test LD": "x_BUY_BOTTOM_DANGER1"},
                 {"DANGER ZONE BUY 2 ,test LD": "x_BUY_BOTTOM_DANGER2"},
                 {"DANGER ZONE BUY 3 ,test LD": "x_BUY_BOTTOM_DANGER3"},
                 {"DANGER ZONE BUY 4 ,test LD": "x_BUY_BOTTOM_DANGER4"},
                 {"DANGER ZONE BUY 5 ,test LD": "x_BUY_BOTTOM_DANGER5"},
                 {"DANGER ZONE BUY 6 ,test LD": "x_BUY_BOTTOM_DANGER6"},
                 {"DANGER ZONE BUY 7 ,test LD": "x_BUY_BOTTOM_DANGER7"},
                 {"DANGER ZONE BUY 8 ,test LD": "x_BUY_BOTTOM_DANGER8"},
                 {"DANGER ZONE BUY 9 ,test LD": "x_BUY_BOTTOM_DANGER9"},
                 {"DANGER ZONE BUY 10 ,test LD": "x_BUY_BOTTOM_DANGER10"},


                 #SLOW DOWNTREND RULES
                 {"SLOW DOWNTREND BUY 1": "x_BUY_SLOW_DOWNTREND1"},
                 {"SLOW DOWNTREND BUY 2": "x_BUY_SLOW_DOWNTREND2"},
                 {"SLOW DOWNTREND BUY 3": "x_BUY_SLOW_DOWNTREND3"},
                 {"SLOW DOWNTREND BUY 4": "x_BUY_SLOW_DOWNTREND4"},
                 {"SLOW DOWNTREND BUY 5": "x_BUY_SLOW_DOWNTREND5"},
                 {"SLOW DOWNTREND BUY 6": "x_BUY_SLOW_DOWNTREND6"},
                 {"SLOW DOWNTREND BUY 7": "x_BUY_SLOW_DOWNTREND7"},
                 {"SLOW DOWNTREND BUY 8": "x_BUY_SLOW_DOWNTREND8"},
                 {"SLOW DOWNTREND BUY 9": "x_BUY_SLOW_DOWNTREND9"},
                 {"SLOW DOWNTREND BUY 10": "x_BUY_SLOW_DOWNTREND10"},
                 {"SLOW DOWNTREND BUY 11": "x_BUY_SLOW_DOWNTREND11"},
                 {"SLOW DOWNTREND BUY 12": "x_BUY_SLOW_DOWNTREND12"},
                 {"SLOW DOWNTREND BUY 13": "x_BUY_SLOW_DOWNTREND13"},
                 {"SLOW DOWNTREND BUY 14": "x_BUY_SLOW_DOWNTREND14"},
                 {"SLOW DOWNTREND BUY 15": "x_BUY_SLOW_DOWNTREND15"},
                 # {"SLOW DOWNTREND BUY 16": "x_BUY_SLOW_DOWNTREND16"},
                 # {"SLOW DOWNTREND BUY 17": "x_BUY_SLOW_DOWNTREND17"},
                 # {"SLOW DOWNTREND BUY 18": "x_BUY_SLOW_DOWNTREND18"},
                 # {"SLOW DOWNTREND BUY 19": "x_BUY_SLOW_DOWNTREND19"},
                 # {"SLOW DOWNTREND BUY 20": "x_BUY_SLOW_DOWNTREND20"},

                 # ANY RULES
                 {"ANY BUY 1": "x_BUY_ANY1"},
                 {"ANY BUY 2": "x_BUY_ANY2"},
                 {"ANY BUY 3": "x_BUY_ANY3"},
                 {"ANY BUY 4": "x_BUY_ANY4"},
                 {"ANY BUY 5": "x_BUY_ANY5"},
                 {"ANY BUY 6": "x_BUY_ANY6"},
                 # {"ANY BUY 7": "x_BUY_ANY7"},
                 # {"ANY BUY 8": "x_BUY_ANY8"},
                 # {"ANY BUY 9": "x_BUY_ANY9"},
                 # {"ANY BUY 10": "x_BUY_ANY10"},

                 # NOTREND RULES
                 {"NOTREND BUY 1": "x_BUY_NOTREND1"},
                 {"NOTREND BUY 2": "x_BUY_NOTREND2"},
                 {"NOTREND BUY 3": "x_BUY_NOTREND3"},
                 {"NOTREND BUY 4": "x_BUY_NOTREND4"},
                 {"NOTREND BUY 5": "x_BUY_NOTREND5"},
                 {"NOTREND BUY 6": "x_BUY_NOTREND6"},
                 # {"NOTREND BUY 7": "x_BUY_NOTREND7"},
                 # {"NOTREND BUY 8": "x_BUY_NOTREND8"},
                 # {"NOTREND BUY 9": "x_BUY_NOTREND9"},
                 # {"NOTREND BUY 10": "x_BUY_NOTREND10"},





                 # #DRAFT SELL RULES
                 # {"SELL 1": "x_Sell1"},
                 # {"SELL 2": "x_Sell2"},
                 # {"SELL 3": "x_Sell3"},
                 # {"SELL 4": "x_Sell4"},
                 # {"SELL 5": "x_Sell5"},


                 # LOW SELL RULES
                 {"LOW SELL 1": "x_SELL_LOW1"},
                 {"LOW SELL 2": "x_SELL_LOW2"},
                 {"LOW SELL 3": "x_SELL_LOW3"},
                 {"LOW SELL 4": "x_SELL_LOW4"},
                 {"LOW SELL 5": "x_SELL_LOW5"},
                 {"LOW SELL 6": "x_SELL_LOW6"},
                 {"LOW SELL 7": "x_SELL_LOW7"},
                 {"LOW SELL 8": "x_SELL_LOW8"},
                 {"LOW SELL 9": "x_SELL_LOW9"},
                 {"LOW SELL 10": "x_SELL_LOW10"},

                 # MID SELL RULES
                 {"MID SELL 1": "x_SELL_MID1"},
                 {"MID SELL 2": "x_SELL_MID2"},
                 {"MID SELL 3": "x_SELL_MID3"},
                 {"MID SELL 4": "x_SELL_MID4"},
                 {"MID SELL 5": "x_SELL_MID5"},
                 {"MID SELL 6": "x_SELL_MID6"},
                 {"MID SELL 7": "x_SELL_MID7"},
                 {"MID SELL 8": "x_SELL_MID8"},
                 {"MID SELL 9": "x_SELL_MID9"},
                 {"MID SELL 10": "x_SELL_MID10"},

                 # HIGH SELL RULES
                 {"HIGH SELL 1": "x_SELL_HIGH1"},
                 {"HIGH SELL 2": "x_SELL_HIGH2"},
                 {"HIGH SELL 3": "x_SELL_HIGH3"},
                 {"HIGH SELL 4": "x_SELL_HIGH4"},
                 {"HIGH SELL 5": "x_SELL_HIGH5"},
                 {"HIGH SELL 6": "x_SELL_HIGH6"},
                 {"HIGH SELL 7": "x_SELL_HIGH7"},
                 {"HIGH SELL 8": "x_SELL_HIGH8"},
                 {"HIGH SELL 9": "x_SELL_HIGH9"},
                 {"HIGH SELL 10": "x_SELL_HIGH10"},

                 # LONG UPTREND SELL RULES
                 {"LONG UPTREND SELL 1": "x_SELL_LONG_UPTREND1"},
                 {"LONG UPTREND SELL 2": "x_SELL_LONG_UPTREND2"},
                 {"LONG UPTREND SELL 3": "x_SELL_LONG_UPTREND3"},
                 {"LONG UPTREND SELL 4": "x_SELL_LONG_UPTREND4"},
                 {"LONG UPTREND SELL 5": "x_SELL_LONG_UPTREND5"},
                 {"LONG UPTREND SELL 6": "x_SELL_LONG_UPTREND6"},
                 {"LONG UPTREND SELL 7": "x_SELL_LONG_UPTREND7"},
                 {"LONG UPTREND SELL 8": "x_SELL_LONG_UPTREND8"},
                 {"LONG UPTREND SELL 9": "x_SELL_LONG_UPTREND9"},
                 {"LONG UPTREND SELL 10": "x_SELL_LONG_UPTREND10"},
                 # {"LONG UPTREND SELL 11": "x_SELL_LONG_UPTREND11"},
                 # {"LONG UPTREND SELL 12": "x_SELL_LONG_UPTREND12"},
                 # {"LONG UPTREND SELL 13": "x_SELL_LONG_UPTREND13"},
                 # {"LONG UPTREND SELL 14": "x_SELL_LONG_UPTREND14"},
                 # {"LONG UPTREND SELL 15": "x_SELL_LONG_UPTREND15"},
                 # {"LONG UPTREND SELL 16": "x_SELL_LONG_UPTREND16"},
                 # {"LONG UPTREND SELL 17": "x_SELL_LONG_UPTREND17"},
                 # {"LONG UPTREND SELL 18": "x_SELL_LONG_UPTREND18"},
                 # {"LONG UPTREND SELL 19": "x_SELL_LONG_UPTREND19"},
                 # {"LONG UPTREND SELL 20": "x_SELL_LONG_UPTREND20"},

                 # LONG DOWNTREND SELL RULES
                 {"LONG DOWNTREND SELL 1": "x_SELL_LONG_DOWNTREND1"},
                 {"LONG DOWNTREND SELL 2": "x_SELL_LONG_DOWNTREND2"},
                 {"LONG DOWNTREND SELL 3": "x_SELL_LONG_DOWNTREND3"},
                 {"LONG DOWNTREND SELL 4": "x_SELL_LONG_DOWNTREND4"},
                 {"LONG DOWNTREND SELL 5": "x_SELL_LONG_DOWNTREND5"},
                 {"LONG DOWNTREND SELL 6": "x_SELL_LONG_DOWNTREND6"},
                 {"LONG DOWNTREND SELL 7": "x_SELL_LONG_DOWNTREND7"},
                 {"LONG DOWNTREND SELL 8": "x_SELL_LONG_DOWNTREND8"},
                 {"LONG DOWNTREND SELL 9": "x_SELL_LONG_DOWNTREND9"},
                 {"LONG DOWNTREND SELL 10": "x_SELL_LONG_DOWNTREND10"},
                 # {"LONG DOWNTREND SELL 11": "x_SELL_LONG_DOWNTREND11"},
                 # {"LONG DOWNTREND SELL 12": "x_SELL_LONG_DOWNTREND12"},
                 # {"LONG DOWNTREND SELL 13": "x_SELL_LONG_DOWNTREND13"},
                 # {"LONG DOWNTREND SELL 14": "x_SELL_LONG_DOWNTREND14"},
                 # {"LONG DOWNTREND SELL 15": "x_SELL_LONG_DOWNTREND15"},
                 # {"LONG DOWNTREND SELL 16": "x_SELL_LONG_DOWNTREND16"},
                 # {"LONG DOWNTREND SELL 17": "x_SELL_LONG_DOWNTREND17"},
                 # {"LONG DOWNTREND SELL 18": "x_SELL_LONG_DOWNTREND18"},
                 # {"LONG DOWNTREND SELL 19": "x_SELL_LONG_DOWNTREND19"},
                 # {"LONG DOWNTREND SELL 20": "x_SELL_LONG_DOWNTREND20"},

                 # SLOW DOWNTREND SELL RULES
                 {"SLOW DOWNTREND SELL 1": "x_SELL_SLOW_DOWNTREND1"},
                 {"SLOW DOWNTREND SELL 2": "x_SELL_SLOW_DOWNTREND2"},
                 {"SLOW DOWNTREND SELL 3": "x_SELL_SLOW_DOWNTREND3"},
                 {"SLOW DOWNTREND SELL 4": "x_SELL_SLOW_DOWNTREND4"},
                 {"SLOW DOWNTREND SELL 5": "x_SELL_SLOW_DOWNTREND5"},
                 {"SLOW DOWNTREND SELL 6": "x_SELL_SLOW_DOWNTREND6"},
                 {"SLOW DOWNTREND SELL 7": "x_SELL_SLOW_DOWNTREND7"},
                 {"SLOW DOWNTREND SELL 8": "x_SELL_SLOW_DOWNTREND8"},
                 {"SLOW DOWNTREND SELL 9": "x_SELL_SLOW_DOWNTREND9"},
                 {"SLOW DOWNTREND SELL 10": "x_SELL_SLOW_DOWNTREND10"},
                 # {"SLOW DOWNTREND SELL 11": "x_SELL_SLOW_DOWNTREND11"},
                 # {"SLOW DOWNTREND SELL 12": "x_SELL_SLOW_DOWNTREND12"},
                 # {"SLOW DOWNTREND SELL 13": "x_SELL_SLOW_DOWNTREND13"},
                 # {"SLOW DOWNTREND SELL 14": "x_SELL_SLOW_DOWNTREND14"},
                 # {"SLOW DOWNTREND SELL 15": "x_SELL_SLOW_DOWNTREND15"},
                 # {"SLOW DOWNTREND SELL 16": "x_SELL_SLOW_DOWNTREND16"},
                 # {"SLOW DOWNTREND SELL 17": "x_SELL_SLOW_DOWNTREND17"},
                 # {"SLOW DOWNTREND SELL 18": "x_SELL_SLOW_DOWNTREND18"},
                 # {"SLOW DOWNTREND SELL 19": "x_SELL_SLOW_DOWNTREND19"},
                 # {"SLOW DOWNTREND SELL 20": "x_SELL_SLOW_DOWNTREND20"},

                 # ANY SELL RULES
                 {"ANY SELL 1": "x_SELL_ANY1"},
                 {"ANY SELL 2": "x_SELL_ANY2"},
                 {"ANY SELL 3": "x_SELL_ANY3"},
                 {"ANY SELL 4": "x_SELL_ANY4"},
                 {"ANY SELL 5": "x_SELL_ANY5"},
                 {"ANY SELL 6": "x_SELL_ANY6"},
                 # {"ANY SELL 7": "x_SELL_ANY7"},
                 # {"ANY SELL 8": "x_SELL_ANY8"},
                 # {"ANY SELL 9": "x_SELL_ANY9"},
                 # {"ANY SELL 10": "x_SELL_ANY10"},

                 # NOTREND SELL RULES
                 {"NOTREND SELL 1": "x_SELL_NOTREND1"},
                 {"NOTREND SELL 2": "x_SELL_NOTREND2"},
                 {"NOTREND SELL 3": "x_SELL_NOTREND3"},
                 {"NOTREND SELL 4": "x_SELL_NOTREND4"},
                 {"NOTREND SELL 5": "x_SELL_NOTREND5"},
                 {"NOTREND SELL 6": "x_SELL_NOTREND6"},
                 # {"NOTREND SELL 7": "x_SELL_NOTREND7"},
                 # {"NOTREND SELL 8": "x_SELL_NOTREND8"},
                 # {"NOTREND SELL 9": "x_SELL_NOTREND9"},
                 # {"NOTREND SELL 10": "x_SELL_NOTREND10"},

                # DANGER ZONE SELL RULES
                 {"BOTTOM_DANGER SELL 1": "x_SELL_BOTTOM_DANGER1"},
                 {"BOTTOM_DANGER SELL 2": "x_SELL_BOTTOM_DANGER2"},
                 {"BOTTOM_DANGER SELL 3": "x_SELL_BOTTOM_DANGER3"},
                 {"BOTTOM_DANGER SELL 4": "x_SELL_BOTTOM_DANGER4"},
                 {"BOTTOM_DANGER SELL 5": "x_SELL_BOTTOM_DANGER5"},

                # UPPER DANGER ZONE SELL RULES
                 {"UPPER_DANGER SELL 1": "x_SELL_UPPER_DANGER1"},
                 {"UPPER_DANGER SELL 2": "x_SELL_UPPER_DANGER2"},
                 {"UPPER_DANGER SELL 3": "x_SELL_UPPER_DANGER3"},
                 {"UPPER_DANGER SELL 4": "x_SELL_UPPER_DANGER4"},
                 {"UPPER_DANGER SELL 5": "x_SELL_UPPER_DANGER5"},
                 {"UPPER_DANGER SELL 6": "x_SELL_UPPER_DANGER6"},
                 {"UPPER_DANGER SELL 7": "x_SELL_UPPER_DANGER7"},
                 {"UPPER_DANGER SELL 8": "x_SELL_UPPER_DANGER8"},
                 {"UPPER_DANGER SELL 9": "x_SELL_UPPER_DANGER9"},
                 {"UPPER_DANGER SELL 10": "x_SELL_UPPER_DANGER10"},

                 ]

hyperopt_loss_functions = ["ShortTradeDurHyperOptLoss", "OnlyProfitHyperOptLoss", "SharpeHyperOptLoss",
                           "SharpeHyperOptLossDaily", "SortinoHyperOptLoss",
                           "SortinoHyperOptLossDaily", "MaxDrawDownHyperOptLoss"]