


MODULE_LIST = [

                            #BUY RULE MODULES
                             "RULES.LOW.x_BUY_LOW1", "x_BUY_LOW1","RULES.LOW.x_BUY_LOW2", "x_BUY_LOW2","RULES.LOW.x_BUY_LOW3", "x_BUY_LOW3",
                             "RULES.LOW.x_BUY_LOW4", "x_BUY_LOW4","RULES.LOW.x_BUY_LOW5", "x_BUY_LOW5","RULES.LOW.x_BUY_LOW6", "x_BUY_LOW6",
                             "RULES.LOW.x_BUY_LOW7", "x_BUY_LOW7","RULES.LOW.x_BUY_LOW8", "x_BUY_LOW8","RULES.LOW.x_BUY_LOW9", "x_BUY_LOW9",
                             "RULES.LOW.x_BUY_LOW10", "x_BUY_LOW10","RULES.LOW.x_BUY_LOW11", "x_BUY_LOW11","RULES.LOW.x_BUY_LOW12", "x_BUY_LOW12",
                             "RULES.LOW.x_BUY_LOW13", "x_BUY_LOW13","RULES.LOW.x_BUY_LOW14", "x_BUY_LOW14","RULES.LOW.x_BUY_LOW15", "x_BUY_LOW15",
                             "RULES.LOW.x_BUY_LOW16", "x_BUY_LOW16","RULES.LOW.x_BUY_LOW17", "x_BUY_LOW17","RULES.LOW.x_BUY_LOW18", "x_BUY_LOW18",
                             "RULES.LOW.x_BUY_LOW19", "x_BUY_LOW19","RULES.LOW.x_BUY_LOW20", "x_BUY_LOW20",


                             "RULES.MID.x_BUY_MID1", "x_BUY_MID1","RULES.MID.x_BUY_MID2", "x_BUY_MID2","RULES.MID.x_BUY_MID3", "x_BUY_MID3",
                             "RULES.MID.x_BUY_MID4", "x_BUY_MID4","RULES.MID.x_BUY_MID5", "x_BUY_MID5","RULES.MID.x_BUY_MID6", "x_BUY_MID6",
                             "RULES.MID.x_BUY_MID7", "x_BUY_MID7","RULES.MID.x_BUY_MID8", "x_BUY_MID8","RULES.MID.x_BUY_MID9", "x_BUY_MID9",
                             "RULES.MID.x_BUY_MID10", "x_BUY_MID10","RULES.MID.x_BUY_MID11", "x_BUY_MID11","RULES.MID.x_BUY_MID12", "x_BUY_MID12",
                             "RULES.MID.x_BUY_MID13", "x_BUY_MID13","RULES.MID.x_BUY_MID14", "x_BUY_MID14","RULES.MID.x_BUY_MID15", "x_BUY_MID15",
                             "RULES.MID.x_BUY_MID16", "x_BUY_MID16","RULES.MID.x_BUY_MID17", "x_BUY_MID17","RULES.MID.x_BUY_MID18", "x_BUY_MID18",
                             "RULES.MID.x_BUY_MID19", "x_BUY_MID19","RULES.MID.x_BUY_MID20", "x_BUY_MID20",


                             "RULES.HIGH.x_BUY_HIGH1", "x_BUY_HIGH1","RULES.HIGH.x_BUY_HIGH2", "x_BUY_HIGH2","RULES.HIGH.x_BUY_HIGH3", "x_BUY_HIGH3",
                             "RULES.HIGH.x_BUY_HIGH4", "x_BUY_HIGH4","RULES.HIGH.x_BUY_HIGH5", "x_BUY_HIGH5","RULES.HIGH.x_BUY_HIGH6", "x_BUY_HIGH6",
                             "RULES.HIGH.x_BUY_HIGH7", "x_BUY_HIGH7","RULES.HIGH.x_BUY_HIGH8", "x_BUY_HIGH8","RULES.HIGH.x_BUY_HIGH9", "x_BUY_HIGH9",
                             "RULES.HIGH.x_BUY_HIGH10", "x_BUY_HIGH10","RULES.HIGH.x_BUY_HIGH11", "x_BUY_HIGH11","RULES.HIGH.x_BUY_HIGH12", "x_BUY_HIGH12",
                             "RULES.HIGH.x_BUY_HIGH13", "x_BUY_HIGH13","RULES.HIGH.x_BUY_HIGH14", "x_BUY_HIGH14","RULES.HIGH.x_BUY_HIGH15", "x_BUY_HIGH15",
                             "RULES.HIGH.x_BUY_HIGH16", "x_BUY_HIGH16","RULES.HIGH.x_BUY_HIGH17", "x_BUY_HIGH17","RULES.HIGH.x_BUY_HIGH18", "x_BUY_HIGH18",
                             "RULES.HIGH.x_BUY_HIGH19", "x_BUY_HIGH19","RULES.HIGH.x_BUY_HIGH20", "x_BUY_HIGH20",



                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND1", "x_BUY_LONG_UPTREND1","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND2", "x_BUY_LONG_UPTREND2","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND3", "x_BUY_LONG_UPTREND3",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND4", "x_BUY_LONG_UPTREND4","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND5", "x_BUY_LONG_UPTREND5","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND6", "x_BUY_LONG_UPTREND6",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND7", "x_BUY_LONG_UPTREND7","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND8", "x_BUY_LONG_UPTREND8","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND9", "x_BUY_LONG_UPTREND9",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND10", "x_BUY_LONG_UPTREND10","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND11", "x_BUY_LONG_UPTREND11","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND12", "x_BUY_LONG_UPTREND12",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND13", "x_BUY_LONG_UPTREND13","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND14", "x_BUY_LONG_UPTREND14","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND15", "x_BUY_LONG_UPTREND15",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND16", "x_BUY_LONG_UPTREND16","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND17", "x_BUY_LONG_UPTREND17","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND18", "x_BUY_LONG_UPTREND18",
                             "RULES.LONG_UPTREND.x_BUY_LONG_UPTREND19", "x_BUY_LONG_UPTREND19","RULES.LONG_UPTREND.x_BUY_LONG_UPTREND20", "x_BUY_LONG_UPTREND20",


                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND1" ,"x_BUY_LONG_DOWNTREND1","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND2" ,"x_BUY_LONG_DOWNTREND2","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND3" ,"x_BUY_LONG_DOWNTREND3",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND4", "x_BUY_LONG_DOWNTREND4","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND5" ,"x_BUY_LONG_DOWNTREND5","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND6" ,"x_BUY_LONG_DOWNTREND6",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND7", "x_BUY_LONG_DOWNTREND7","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND8" ,"x_BUY_LONG_DOWNTREND8","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND9" ,"x_BUY_LONG_DOWNTREND9",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND10", "x_BUY_LONG_DOWNTREND10","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND11" ,"x_BUY_LONG_DOWNTREND11","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND12" ,"x_BUY_LONG_DOWNTREND12",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND13", "x_BUY_LONG_DOWNTREND13","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND14" ,"x_BUY_LONG_DOWNTREND14","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND15" ,"x_BUY_LONG_DOWNTREND15",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND16", "x_BUY_LONG_DOWNTREND16","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND17" ,"x_BUY_LONG_DOWNTREND17","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND18" ,"x_BUY_LONG_DOWNTREND18",
                             "RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND19", "x_BUY_LONG_DOWNTREND19","RULES.LONG_DOWNTREND.x_BUY_LONG_DOWNTREND20" ,"x_BUY_LONG_DOWNTREND20",

                             "RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER1" ,"x_BUY_BOTTOM_DANGER1","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER2" ,"x_BUY_BOTTOM_DANGER2","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER3" ,"x_BUY_BOTTOM_DANGER3",
                             "RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER4", "x_BUY_BOTTOM_DANGER4","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER5" ,"x_BUY_BOTTOM_DANGER5","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER6" ,"x_BUY_BOTTOM_DANGER6",
                                "RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER7", "x_BUY_BOTTOM_DANGER7","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER8" ,"x_BUY_BOTTOM_DANGER8","RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER9" ,"x_BUY_BOTTOM_DANGER9",
                                "RULES.BOTTOM_DANGER.x_BUY_BOTTOM_DANGER10", "x_BUY_BOTTOM_DANGER10",


                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND1", "x_BUY_SLOW_DOWNTREND1","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND2", "x_BUY_SLOW_DOWNTREND2","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND3", "x_BUY_SLOW_DOWNTREND3",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND4", "x_BUY_SLOW_DOWNTREND4","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND5", "x_BUY_SLOW_DOWNTREND5","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND6", "x_BUY_SLOW_DOWNTREND6",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND7", "x_BUY_SLOW_DOWNTREND7","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND8", "x_BUY_SLOW_DOWNTREND8","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND9", "x_BUY_SLOW_DOWNTREND9",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND10", "x_BUY_SLOW_DOWNTREND10","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND11", "x_BUY_SLOW_DOWNTREND11","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND12", "x_BUY_SLOW_DOWNTREND12",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND13", "x_BUY_SLOW_DOWNTREND13","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND14", "x_BUY_SLOW_DOWNTREND14","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND15", "x_BUY_SLOW_DOWNTREND15",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND16", "x_BUY_SLOW_DOWNTREND16","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND17", "x_BUY_SLOW_DOWNTREND17","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND18", "x_BUY_SLOW_DOWNTREND18",
                             "RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND19", "x_BUY_SLOW_DOWNTREND19","RULES.SLOW_DOWNTREND.x_BUY_SLOW_DOWNTREND20", "x_BUY_SLOW_DOWNTREND20",


                             "RULES.ANY.x_BUY_ANY1", "x_BUY_ANY1","RULES.ANY.x_BUY_ANY2", "x_BUY_ANY2","RULES.ANY.x_BUY_ANY3", "x_BUY_ANY3",
                             "RULES.ANY.x_BUY_ANY4", "x_BUY_ANY4","RULES.ANY.x_BUY_ANY5", "x_BUY_ANY5","RULES.ANY.x_BUY_ANY6", "x_BUY_ANY6",
                             "RULES.ANY.x_BUY_ANY7", "x_BUY_ANY7","RULES.ANY.x_BUY_ANY8", "x_BUY_ANY8","RULES.ANY.x_BUY_ANY9", "x_BUY_ANY9",
                             "RULES.ANY.x_BUY_ANY10", "x_BUY_ANY10","RULES.ANY.x_BUY_ANY11", "x_BUY_ANY11","RULES.ANY.x_BUY_ANY12", "x_BUY_ANY12",
                             "RULES.ANY.x_BUY_ANY13", "x_BUY_ANY13","RULES.ANY.x_BUY_ANY14", "x_BUY_ANY14","RULES.ANY.x_BUY_ANY15", "x_BUY_ANY15",
                             "RULES.ANY.x_BUY_ANY16", "x_BUY_ANY16","RULES.ANY.x_BUY_ANY17", "x_BUY_ANY17","RULES.ANY.x_BUY_ANY18", "x_BUY_ANY18",
                             "RULES.ANY.x_BUY_ANY19", "x_BUY_ANY19","RULES.ANY.x_BUY_ANY20", "x_BUY_ANY20",

                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER1", "x_BUY_UPPER_DANGER1","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER2", "x_BUY_UPPER_DANGER2","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER3", "x_BUY_UPPER_DANGER3",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER4", "x_BUY_UPPER_DANGER4","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER5", "x_BUY_UPPER_DANGER5","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER6", "x_BUY_UPPER_DANGER6",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER7", "x_BUY_UPPER_DANGER7","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER8", "x_BUY_UPPER_DANGER8","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER9", "x_BUY_UPPER_DANGER9",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER10", "x_BUY_UPPER_DANGER10","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER11", "x_BUY_UPPER_DANGER11","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER12", "x_BUY_UPPER_DANGER12",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER13", "x_BUY_UPPER_DANGER13","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER14", "x_BUY_UPPER_DANGER14","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER15", "x_BUY_UPPER_DANGER15",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER16", "x_BUY_UPPER_DANGER16","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER17", "x_BUY_UPPER_DANGER17","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER18", "x_BUY_UPPER_DANGER18",
                             "RULES.UPPER_DANGER.x_BUY_UPPER_DANGER19", "x_BUY_UPPER_DANGER19","RULES.UPPER_DANGER.x_BUY_UPPER_DANGER20", "x_BUY_UPPER_DANGER20",

                             "RULES.NOTREND.x_BUY_NOTREND1", "x_BUY_NOTREND1","RULES.NOTREND.x_BUY_NOTREND2", "x_BUY_NOTREND2","RULES.NOTREND.x_BUY_NOTREND3", "x_BUY_NOTREND3",
                             "RULES.NOTREND.x_BUY_NOTREND4", "x_BUY_NOTREND4","RULES.NOTREND.x_BUY_NOTREND5", "x_BUY_NOTREND5","RULES.NOTREND.x_BUY_NOTREND6", "x_BUY_NOTREND6",
                             "RULES.NOTREND.x_BUY_NOTREND7", "x_BUY_NOTREND7","RULES.NOTREND.x_BUY_NOTREND8", "x_BUY_NOTREND8","RULES.NOTREND.x_BUY_NOTREND9", "x_BUY_NOTREND9",
                             "RULES.NOTREND.x_BUY_NOTREND10", "x_BUY_NOTREND10","RULES.NOTREND.x_BUY_NOTREND11", "x_BUY_NOTREND11","RULES.NOTREND.x_BUY_NOTREND12", "x_BUY_NOTREND12",
                             "RULES.NOTREND.x_BUY_NOTREND13", "x_BUY_NOTREND13","RULES.NOTREND.x_BUY_NOTREND14", "x_BUY_NOTREND14","RULES.NOTREND.x_BUY_NOTREND15", "x_BUY_NOTREND15",
                             "RULES.NOTREND.x_BUY_NOTREND16", "x_BUY_NOTREND16","RULES.NOTREND.x_BUY_NOTREND17", "x_BUY_NOTREND17","RULES.NOTREND.x_BUY_NOTREND18", "x_BUY_NOTREND18",
                             "RULES.NOTREND.x_BUY_NOTREND19", "x_BUY_NOTREND19","RULES.NOTREND.x_BUY_NOTREND20", "x_BUY_NOTREND20",

                            #NOSTALGIA ONES

                            "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_OLD", "NOSTALGIA_OLD","RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_LONG_UPTREND", "NOSTALGIA_LONG_UPTREND",
                             "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_LONG_DOWNTREND", "NOSTALGIA_LONG_DOWNTREND","RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_SLOW_DOWNTREND", "NOSTALGIA_SLOW_DOWNTREND",
                             "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_HIGH", "NOSTALGIA_HIGH","RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_LOW", "NOSTALGIA_LOW",
                             "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_MID", "NOSTALGIA_MID","RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_BOTTOM_DANGER", "NOSTALGIA_BOTTOM_DANGER",
                            "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_ANY", "NOSTALGIA_ANY","RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_NOTREND", "NOSTALGIA_NOTREND",
                            "RULES.CUSTOM.OG_NOSTALGIA.NOSTALGIA_UPPER_DANGER", "NOSTALGIA_UPPER_DANGER",

                             "RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_LONG_UPTREND", "BEAR_4_INFINITY_LONG_UPTREND","RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_ANY", "BEAR_4_INFINITY_ANY",
                             "RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_LONG_DOWNTREND", "BEAR_4_INFINITY_LONG_DOWNTREND","RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_SLOW_DOWNTREND", "BEAR_4_INFINITY_SLOW_DOWNTREND",
                             "RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_HIGH", "BEAR_4_INFINITY_HIGH","RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_LOW", "BEAR_4_INFINITY_LOW",
                             "RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_MID", "BEAR_4_INFINITY_MID","RULES.CUSTOM.BEAR_4_INFINITY.BEAR_4_INFINITY_BOTTOM_DANGER", "BEAR_4_INFINITY_BOTTOM_DANGER",

                             "RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_LONG_UPTREND", "BULL_4_INFINITY_LONG_UPTREND","RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_ANY", "BULL_4_INFINITY_ANY",
                             "RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_LONG_DOWNTREND", "BULL_4_INFINITY_LONG_DOWNTREND","RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_SLOW_DOWNTREND", "BULL_4_INFINITY_SLOW_DOWNTREND",
                             "RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_HIGH", "BULL_4_INFINITY_HIGH","RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_LOW", "BULL_4_INFINITY_LOW",
                             "RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_MID", "BULL_4_INFINITY_MID","RULES.CUSTOM.BULL_4_INFINITY.BULL_4_INFINITY_BOTTOM_DANGER", "BULL_4_INFINITY_BOTTOM_DANGER",

                             "RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_LONG_UPTREND", "DOWNTREND_4_INFINITY_LONG_UPTREND","RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_ANY", "DOWNTREND_4_INFINITY_ANY",
                             "RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_LONG_DOWNTREND", "DOWNTREND_4_INFINITY_LONG_DOWNTREND","RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_SLOW_DOWNTREND", "DOWNTREND_4_INFINITY_SLOW_DOWNTREND",
                             "RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_HIGH", "DOWNTREND_4_INFINITY_HIGH","RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_LOW", "DOWNTREND_4_INFINITY_LOW",
                             "RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_MID", "DOWNTREND_4_INFINITY_MID","RULES.CUSTOM.DOWNTREND_4_INFINITY.DOWNTREND_4_INFINITY_BOTTOM_DANGER", "DOWNTREND_4_INFINITY_BOTTOM_DANGER",

                             "RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_LONG_UPTREND", "UPTREND_4_INFINITY_LONG_UPTREND","RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_ANY", "UPTREND_4_INFINITY_ANY",
                             "RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_LONG_DOWNTREND", "UPTREND_4_INFINITY_LONG_DOWNTREND","RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_SLOW_DOWNTREND", "UPTREND_4_INFINITY_SLOW_DOWNTREND",
                             "RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_HIGH", "UPTREND_4_INFINITY_HIGH","RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_LOW", "UPTREND_4_INFINITY_LOW",
                             "RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_MID", "UPTREND_4_INFINITY_MID","RULES.CUSTOM.UPTREND_4_INFINITY.UPTREND_4_INFINITY_BOTTOM_DANGER", "UPTREND_4_INFINITY_BOTTOM_DANGER",

                            #SELLER NOSTALGIA ONES

                            "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_OLD", "SELLER_NOSTALGIA_OLD","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_LONG_UPTREND", "SELLER_NOSTALGIA_LONG_UPTREND",
                             "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_LONG_DOWNTREND", "SELLER_NOSTALGIA_LONG_DOWNTREND","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_SLOW_DOWNTREND", "SELLER_NOSTALGIA_SLOW_DOWNTREND",
                             "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_HIGH", "SELLER_NOSTALGIA_HIGH","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_LOW", "SELLER_NOSTALGIA_LOW",
                             "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_MID", "SELLER_NOSTALGIA_MID","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_UPPER_DANGER", "SELLER_NOSTALGIA_UPPER_DANGER",
                            "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_UPPER_DANGER_MID", "SELLER_NOSTALGIA_UPPER_DANGER_MID","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_UPPER_DANGER_LOW", "SELLER_NOSTALGIA_UPPER_DANGER_LOW",
                            "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_ANY", "SELLER_NOSTALGIA_ANY","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_BOTTOM_DANGER", "SELLER_NOSTALGIA_BOTTOM_DANGER",
                            "SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_NOTREND", "SELLER_NOSTALGIA_NOTREND","SELL_RULES.CUSTOM.OG_NOSTALGIA.SELLER_NOSTALGIA_LONG_UPTREND_MIDLOW","SELLER_NOSTALGIA_LONG_UPTREND_MIDLOW",

                             "SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_LONG_UPTREND", "SELLER_BEAR_4_INFINITY_LONG_UPTREND","SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_ANY", "SELLER_BEAR_4_INFINITY_ANY",
                             "SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_LONG_DOWNTREND", "SELLER_BEAR_4_INFINITY_LONG_DOWNTREND","SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_SLOW_DOWNTREND", "SELLER_BEAR_4_INFINITY_SLOW_DOWNTREND",
                             "SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_HIGH", "SELLER_BEAR_4_INFINITY_HIGH","SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_LOW", "SELLER_BEAR_4_INFINITY_LOW",
                             "SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_MID", "SELLER_BEAR_4_INFINITY_MID","SELL_RULES.CUSTOM.BEAR_4_INFINITY.SELLER_BEAR_4_INFINITY_UPPER_DANGER", "SELLER_BEAR_4_INFINITY_UPPER_DANGER",

                             "SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_LONG_UPTREND", "SELLER_BULL_4_INFINITY_LONG_UPTREND","SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_ANY", "SELLER_BULL_4_INFINITY_ANY",
                             "SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_LONG_DOWNTREND", "SELLER_BULL_4_INFINITY_LONG_DOWNTREND","SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_SLOW_DOWNTREND", "SELLER_BULL_4_INFINITY_SLOW_DOWNTREND",
                             "SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_HIGH", "SELLER_BULL_4_INFINITY_HIGH","SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_LOW", "SELLER_BULL_4_INFINITY_LOW",
                             "SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_MID", "SELLER_BULL_4_INFINITY_MID","SELL_RULES.CUSTOM.BULL_4_INFINITY.SELLER_BULL_4_INFINITY_UPPER_DANGER", "SELLER_BULL_4_INFINITY_UPPER_DANGER",

                             "SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_LONG_UPTREND", "SELLER_DOWNTREND_4_INFINITY_LONG_UPTREND","SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_ANY", "SELLER_DOWNTREND_4_INFINITY_ANY",
                             "SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_LONG_DOWNTREND", "SELLER_DOWNTREND_4_INFINITY_LONG_DOWNTREND","SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_SLOW_DOWNTREND", "SELLER_DOWNTREND_4_INFINITY_SLOW_DOWNTREND",
                             "SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_HIGH", "SELLER_DOWNTREND_4_INFINITY_HIGH","SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_LOW", "SELLER_DOWNTREND_4_INFINITY_LOW",
                             "SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_MID", "SELLER_DOWNTREND_4_INFINITY_MID","SELL_RULES.CUSTOM.DOWNTREND_4_INFINITY.SELLER_DOWNTREND_4_INFINITY_UPPER_DANGER", "SELLER_DOWNTREND_4_INFINITY_UPPER_DANGER",

                             "SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_LONG_UPTREND", "SELLER_UPTREND_4_INFINITY_LONG_UPTREND","SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_ANY", "SELLER_UPTREND_4_INFINITY_ANY",
                             "SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_LONG_DOWNTREND", "SELLER_UPTREND_4_INFINITY_LONG_DOWNTREND","SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_SLOW_DOWNTREND", "SELLER_UPTREND_4_INFINITY_SLOW_DOWNTREND",
                             "SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_HIGH", "SELLER_UPTREND_4_INFINITY_HIGH","SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_LOW", "SELLER_UPTREND_4_INFINITY_LOW",
                             "SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_MID", "SELLER_UPTREND_4_INFINITY_MID","SELL_RULES.CUSTOM.UPTREND_4_INFINITY.SELLER_UPTREND_4_INFINITY_UPPER_DANGER", "SELLER_UPTREND_4_INFINITY_UPPER_DANGER",


                            #SELL RULE MODULES
                            "SELL_RULES.LOW.x_SELL_LOW1", "x_SELL_LOW1","SELL_RULES.LOW.x_SELL_LOW2", "x_SELL_LOW2","SELL_RULES.LOW.x_SELL_LOW3", "x_SELL_LOW3",
                             "SELL_RULES.LOW.x_SELL_LOW4", "x_SELL_LOW4","SELL_RULES.LOW.x_SELL_LOW5", "x_SELL_LOW5","SELL_RULES.LOW.x_SELL_LOW6", "x_SELL_LOW6",
                             "SELL_RULES.LOW.x_SELL_LOW7", "x_SELL_LOW7","SELL_RULES.LOW.x_SELL_LOW8", "x_SELL_LOW8","SELL_RULES.LOW.x_SELL_LOW9", "x_SELL_LOW9",
                             "SELL_RULES.LOW.x_SELL_LOW10", "x_SELL_LOW10","SELL_RULES.LOW.x_SELL_LOW11", "x_SELL_LOW11","SELL_RULES.LOW.x_SELL_LOW12", "x_SELL_LOW12",
                             "SELL_RULES.LOW.x_SELL_LOW13", "x_SELL_LOW13","SELL_RULES.LOW.x_SELL_LOW14", "x_SELL_LOW14","SELL_RULES.LOW.x_SELL_LOW15", "x_SELL_LOW15",
                             "SELL_RULES.LOW.x_SELL_LOW16", "x_SELL_LOW16","SELL_RULES.LOW.x_SELL_LOW17", "x_SELL_LOW17","SELL_RULES.LOW.x_SELL_LOW18", "x_SELL_LOW18",
                             "SELL_RULES.LOW.x_SELL_LOW19", "x_SELL_LOW19","SELL_RULES.LOW.x_SELL_LOW20", "x_SELL_LOW20",


                             "SELL_RULES.MID.x_SELL_MID1", "x_SELL_MID1","SELL_RULES.MID.x_SELL_MID2", "x_SELL_MID2","SELL_RULES.MID.x_SELL_MID3", "x_SELL_MID3",
                             "SELL_RULES.MID.x_SELL_MID4", "x_SELL_MID4","SELL_RULES.MID.x_SELL_MID5", "x_SELL_MID5","SELL_RULES.MID.x_SELL_MID6", "x_SELL_MID6",
                             "SELL_RULES.MID.x_SELL_MID7", "x_SELL_MID7","SELL_RULES.MID.x_SELL_MID8", "x_SELL_MID8","SELL_RULES.MID.x_SELL_MID9", "x_SELL_MID9",
                             "SELL_RULES.MID.x_SELL_MID10", "x_SELL_MID10","SELL_RULES.MID.x_SELL_MID11", "x_SELL_MID11","SELL_RULES.MID.x_SELL_MID12", "x_SELL_MID12",
                             "SELL_RULES.MID.x_SELL_MID13", "x_SELL_MID13","SELL_RULES.MID.x_SELL_MID14", "x_SELL_MID14","SELL_RULES.MID.x_SELL_MID15", "x_SELL_MID15",
                             "SELL_RULES.MID.x_SELL_MID16", "x_SELL_MID16","SELL_RULES.MID.x_SELL_MID17", "x_SELL_MID17","SELL_RULES.MID.x_SELL_MID18", "x_SELL_MID18",
                             "SELL_RULES.MID.x_SELL_MID19", "x_SELL_MID19","SELL_RULES.MID.x_SELL_MID20", "x_SELL_MID20",


                             "SELL_RULES.HIGH.x_SELL_HIGH1", "x_SELL_HIGH1","SELL_RULES.HIGH.x_SELL_HIGH2", "x_SELL_HIGH2","SELL_RULES.HIGH.x_SELL_HIGH3", "x_SELL_HIGH3",
                             "SELL_RULES.HIGH.x_SELL_HIGH4", "x_SELL_HIGH4","SELL_RULES.HIGH.x_SELL_HIGH5", "x_SELL_HIGH5","SELL_RULES.HIGH.x_SELL_HIGH6", "x_SELL_HIGH6",
                             "SELL_RULES.HIGH.x_SELL_HIGH7", "x_SELL_HIGH7","SELL_RULES.HIGH.x_SELL_HIGH8", "x_SELL_HIGH8","SELL_RULES.HIGH.x_SELL_HIGH9", "x_SELL_HIGH9",
                             "SELL_RULES.HIGH.x_SELL_HIGH10", "x_SELL_HIGH10","SELL_RULES.HIGH.x_SELL_HIGH11", "x_SELL_HIGH11","SELL_RULES.HIGH.x_SELL_HIGH12", "x_SELL_HIGH12",
                             "SELL_RULES.HIGH.x_SELL_HIGH13", "x_SELL_HIGH13","SELL_RULES.HIGH.x_SELL_HIGH14", "x_SELL_HIGH14","SELL_RULES.HIGH.x_SELL_HIGH15", "x_SELL_HIGH15",
                             "SELL_RULES.HIGH.x_SELL_HIGH16", "x_SELL_HIGH16","SELL_RULES.HIGH.x_SELL_HIGH17", "x_SELL_HIGH17","SELL_RULES.HIGH.x_SELL_HIGH18", "x_SELL_HIGH18",
                             "SELL_RULES.HIGH.x_SELL_HIGH19", "x_SELL_HIGH19","SELL_RULES.HIGH.x_SELL_HIGH20", "x_SELL_HIGH20",



                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND1", "x_SELL_LONG_UPTREND1","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND2", "x_SELL_LONG_UPTREND2","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND3", "x_SELL_LONG_UPTREND3",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND4", "x_SELL_LONG_UPTREND4","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND5", "x_SELL_LONG_UPTREND5","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND6", "x_SELL_LONG_UPTREND6",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND7", "x_SELL_LONG_UPTREND7","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND8", "x_SELL_LONG_UPTREND8","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND9", "x_SELL_LONG_UPTREND9",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND10", "x_SELL_LONG_UPTREND10","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND11", "x_SELL_LONG_UPTREND11","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND12", "x_SELL_LONG_UPTREND12",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND13", "x_SELL_LONG_UPTREND13","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND14", "x_SELL_LONG_UPTREND14","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND15", "x_SELL_LONG_UPTREND15",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND16", "x_SELL_LONG_UPTREND16","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND17", "x_SELL_LONG_UPTREND17","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND18", "x_SELL_LONG_UPTREND18",
                             "SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND19", "x_SELL_LONG_UPTREND19","SELL_RULES.LONG_UPTREND.x_SELL_LONG_UPTREND20", "x_SELL_LONG_UPTREND20",


                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND1" ,"x_SELL_LONG_DOWNTREND1","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND2" ,"x_SELL_LONG_DOWNTREND2","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND3" ,"x_SELL_LONG_DOWNTREND3",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND4", "x_SELL_LONG_DOWNTREND4","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND5" ,"x_SELL_LONG_DOWNTREND5","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND6" ,"x_SELL_LONG_DOWNTREND6",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND7", "x_SELL_LONG_DOWNTREND7","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND8" ,"x_SELL_LONG_DOWNTREND8","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND9" ,"x_SELL_LONG_DOWNTREND9",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND10", "x_SELL_LONG_DOWNTREND10","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND11" ,"x_SELL_LONG_DOWNTREND11","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND12" ,"x_SELL_LONG_DOWNTREND12",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND13", "x_SELL_LONG_DOWNTREND13","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND14" ,"x_SELL_LONG_DOWNTREND14","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND15" ,"x_SELL_LONG_DOWNTREND15",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND16", "x_SELL_LONG_DOWNTREND16","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND17" ,"x_SELL_LONG_DOWNTREND17","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND18" ,"x_SELL_LONG_DOWNTREND18",
                             "SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND19", "x_SELL_LONG_DOWNTREND19","SELL_RULES.LONG_DOWNTREND.x_SELL_LONG_DOWNTREND20" ,"x_SELL_LONG_DOWNTREND20",


                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND1", "x_SELL_SLOW_DOWNTREND1","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND2", "x_SELL_SLOW_DOWNTREND2","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND3", "x_SELL_SLOW_DOWNTREND3",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND4", "x_SELL_SLOW_DOWNTREND4","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND5", "x_SELL_SLOW_DOWNTREND5","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND6", "x_SELL_SLOW_DOWNTREND6",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND7", "x_SELL_SLOW_DOWNTREND7","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND8", "x_SELL_SLOW_DOWNTREND8","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND9", "x_SELL_SLOW_DOWNTREND9",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND10", "x_SELL_SLOW_DOWNTREND10","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND11", "x_SELL_SLOW_DOWNTREND11","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND12", "x_SELL_SLOW_DOWNTREND12",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND13", "x_SELL_SLOW_DOWNTREND13","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND14", "x_SELL_SLOW_DOWNTREND14","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND15", "x_SELL_SLOW_DOWNTREND15",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND16", "x_SELL_SLOW_DOWNTREND16","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND17", "x_SELL_SLOW_DOWNTREND17","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND18", "x_SELL_SLOW_DOWNTREND18",
                             "SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND19", "x_SELL_SLOW_DOWNTREND19","SELL_RULES.SLOW_DOWNTREND.x_SELL_SLOW_DOWNTREND20", "x_SELL_SLOW_DOWNTREND20",


                             "SELL_RULES.ANY.x_SELL_ANY1", "x_SELL_ANY1","SELL_RULES.ANY.x_SELL_ANY2", "x_SELL_ANY2","SELL_RULES.ANY.x_SELL_ANY3", "x_SELL_ANY3",
                             "SELL_RULES.ANY.x_SELL_ANY4", "x_SELL_ANY4","SELL_RULES.ANY.x_SELL_ANY5", "x_SELL_ANY5","SELL_RULES.ANY.x_SELL_ANY6", "x_SELL_ANY6",
                             "SELL_RULES.ANY.x_SELL_ANY7", "x_SELL_ANY7","SELL_RULES.ANY.x_SELL_ANY8", "x_SELL_ANY8","SELL_RULES.ANY.x_SELL_ANY9", "x_SELL_ANY9",
                             "SELL_RULES.ANY.x_SELL_ANY10", "x_SELL_ANY10","SELL_RULES.ANY.x_SELL_ANY11", "x_SELL_ANY11","SELL_RULES.ANY.x_SELL_ANY12", "x_SELL_ANY12",
                             "SELL_RULES.ANY.x_SELL_ANY13", "x_SELL_ANY13","SELL_RULES.ANY.x_SELL_ANY14", "x_SELL_ANY14","SELL_RULES.ANY.x_SELL_ANY15", "x_SELL_ANY15",
                             "SELL_RULES.ANY.x_SELL_ANY16", "x_SELL_ANY16","SELL_RULES.ANY.x_SELL_ANY17", "x_SELL_ANY17","SELL_RULES.ANY.x_SELL_ANY18", "x_SELL_ANY18",
                             "SELL_RULES.ANY.x_SELL_ANY19", "x_SELL_ANY19","SELL_RULES.ANY.x_SELL_ANY20", "x_SELL_ANY20",

                             "SELL_RULES.NOTREND.x_SELL_NOTREND1", "x_SELL_NOTREND1","SELL_RULES.NOTREND.x_SELL_NOTREND2", "x_SELL_NOTREND2","SELL_RULES.NOTREND.x_SELL_NOTREND3", "x_SELL_NOTREND3",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND4", "x_SELL_NOTREND4","SELL_RULES.NOTREND.x_SELL_NOTREND5", "x_SELL_NOTREND5","SELL_RULES.NOTREND.x_SELL_NOTREND6", "x_SELL_NOTREND6",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND7", "x_SELL_NOTREND7","SELL_RULES.NOTREND.x_SELL_NOTREND8", "x_SELL_NOTREND8","SELL_RULES.NOTREND.x_SELL_NOTREND9", "x_SELL_NOTREND9",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND10", "x_SELL_NOTREND10","SELL_RULES.NOTREND.x_SELL_NOTREND11", "x_SELL_NOTREND11","SELL_RULES.NOTREND.x_SELL_NOTREND12", "x_SELL_NOTREND12",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND13", "x_SELL_NOTREND13","SELL_RULES.NOTREND.x_SELL_NOTREND14", "x_SELL_NOTREND14","SELL_RULES.NOTREND.x_SELL_NOTREND15", "x_SELL_NOTREND15",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND16", "x_SELL_NOTREND16","SELL_RULES.NOTREND.x_SELL_NOTREND17", "x_SELL_NOTREND17","SELL_RULES.NOTREND.x_SELL_NOTREND18", "x_SELL_NOTREND18",
                             "SELL_RULES.NOTREND.x_SELL_NOTREND19", "x_SELL_NOTREND19","SELL_RULES.NOTREND.x_SELL_NOTREND20", "x_SELL_NOTREND20",

                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER1", "x_SELL_UPPER_DANGER1","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER2", "x_SELL_UPPER_DANGER2","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER3", "x_SELL_UPPER_DANGER3",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER4", "x_SELL_UPPER_DANGER4","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER5", "x_SELL_UPPER_DANGER5","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER6", "x_SELL_UPPER_DANGER6",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER7", "x_SELL_UPPER_DANGER7","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER8", "x_SELL_UPPER_DANGER8","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER9", "x_SELL_UPPER_DANGER9",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER10", "x_SELL_UPPER_DANGER10","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER11", "x_SELL_UPPER_DANGER11","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER12", "x_SELL_UPPER_DANGER12",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER13", "x_SELL_UPPER_DANGER13","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER14", "x_SELL_UPPER_DANGER14","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER15", "x_SELL_UPPER_DANGER15",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER16", "x_SELL_UPPER_DANGER16","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER17", "x_SELL_UPPER_DANGER17","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER18", "x_SELL_UPPER_DANGER18",
                             "SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER19", "x_SELL_UPPER_DANGER19","SELL_RULES.UPPER_DANGER.x_SELL_UPPER_DANGER20", "x_SELL_UPPER_DANGER20",

                            "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER1", "x_SELL_BOTTOM_DANGER1","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER2", "x_SELL_BOTTOM_DANGER2","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER3", "x_SELL_BOTTOM_DANGER3",
                             "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER4", "x_SELL_BOTTOM_DANGER4","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER5", "x_SELL_BOTTOM_DANGER5","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER6", "x_SELL_BOTTOM_DANGER6",
                             "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER7", "x_SELL_BOTTOM_DANGER7","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER8", "x_SELL_BOTTOM_DANGER8","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER9", "x_SELL_BOTTOM_DANGER9",
                             "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER10", "x_SELL_BOTTOM_DANGER10","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER11", "x_SELL_BOTTOM_DANGER11","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER12", "x_SELL_BOTTOM_DANGER12",
                             # "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER13", "x_SELL_BOTTOM_DANGER13","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER14", "x_SELL_BOTTOM_DANGER14","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER15", "x_SELL_BOTTOM_DANGER15",
                             # "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER16", "x_SELL_BOTTOM_DANGER16","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER17", "x_SELL_BOTTOM_DANGER17","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER18", "x_SELL_BOTTOM_DANGER18",
                             # "SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER19", "x_SELL_BOTTOM_DANGER19","SELL_RULES.BOTTOM_DANGER.x_SELL_BOTTOM_DANGER20", "x_SELL_BOTTOM_DANGER20",


                            "COMMON.COMMON_FUNCTIONS", "COMMON.CONSTANTS","COMMON.TA_FUNCTIONS","COMMON.STAKES","COMMON_FUNCTIONS", "CONSTANTS","TA_FUNCTIONS","STAKES","POPULATE_INDICATORS",
                            "HELPER.BUYS","HELPER.SELLS","HELPER.BUYER_NOSTALGIA","BUYER_NOSTALGIA","HELPER.SELLER_NOSTALGIA","SELLER_NOSTALGIA","RULES.PREVENTS","PREVENTS","SELL_RULES.PREVENTS","SELL_PREVENTS",

                            "INDICATORS.POPULATE_INDICATORS","POPULATE_INDICATORS","INDICATORS.INDICATORS1","INDICATORS1","INDICATORS.INDICATORS1_RARE","INDICATORS1_RARE",
                            "INDICATORS.INDICATORS2","INDICATORS2","INDICATORS.INDICATORS2_RARE","INDICATORS2_RARE","INDICATORS.INDICATORS3","INDICATORS3",
                            "INDICATORS.INDICATORS3_RARE","INDICATORS3_RARE","INDICATORS.INDICATORS1H","INDICATORS1H","INDICATORS.INDICATORS1D","INDICATORS1D",
                            "INDICATORS.INDICATORS_OTHER","INDICATORS_OTHER",

                            "AltcoinTrader15","z____placeholders______","Constants","BUYS","SELLS","ALL_RULES_BUYS","ALL_RULES_SELLS"

                            "BuyerDevDangerZone","buyer_dev_BOTTOM_DANGER","BuyerDevDowntrendUpswing","BuyerDevHigh","buyer_dev_HIGH",
                            "BuyerDevLongDowntrend","buyer_dev_LONG_DOWNTREND","BuyerDevLongUptrend","buyer_dev_LONG_UPTREND","BuyerDevLow","buyer_dev_LOW",
                            "BuyerDevMid","buyer_dev_MID","BuyerDevSlowDowntrend","buyer_dev_SLOW_DOWNTREND","BuyerDevUpperDangerZone","buyer_dev_UPPER_DANGER",
                            "BuyerDevAny","buyer_dev_ANY","BuyerDevNotrend","buyer_dev_NOTREND",

                            "SellerDevDangerZone","seller_dev_BOTTOM_DANGER","SellerDevDowntrendUpswing","SellerDevHigh","seller_dev_HIGH",
                            "SellerDevLongDowntrend","seller_dev_LONG_DOWNTREND","SellerDevLongUptrend","seller_dev_LONG_UPTREND","SellerDevLow","seller_dev_LOW",
                            "SellerDevMid","seller_dev_MID","SellerDevSlowDowntrend","seller_dev_SLOW_DOWNTREND","SellerDevUpperDangerZone","seller_dev_UPPER_DANGER",
                            "SellerDevAny", "seller_dev_ANY", "SellerDevNotrend", "seller_dev_NOTREND",

                            ]